# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8771be053631c17589fc6b7919b116a30f04da33be14dae67ded17d85eefebfb37700fe9a15e51f7db751b141d93483aa39fa7db4efade0fc53b145ef0febd7b

test:
  secret_key_base: a5029a9387058b0764e020b8dff3913ff15fc02a11e340e40764426f5d1737d6676b44025149141f14996ad164c629cc1e8cdb6a50dc04e010eaf29e5a170de9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
